### ISSUE TITLE
Why is `cmd` be implemented as a function and not a CE operation?

### ISSUE THREAD

**Issue by MangelMaxime** [slaveOftime/Fun.Build#23] opened 2023-01-30 13:25 UTC
Hello,

while looking at the source code I found that `cmd` is implemented using as a function and not a CE operation.

https://github.com/slaveOftime/Fun.Build/blob/d4ea016ff5613c0f8a7e74612f67590f1bf8ab29/Fun.Build/BuiltinCmds.fs#L116-L117

Would it be possible to implement it using CE so user can overload it if they need to?

**Comment by albertwoo** [comment] 2023-02-09 02:05
I tried that before, I think the problem is because CE is handling FormattableString different. And it blocked me to add it to CE.

**Comment by MangelMaxime** [comment] 2023-02-15 09:11
We need to investigate that because this is causing a problem if you want to access Env variables for running your command.

```
runSensitive (fun ctx ->
    let myEnvVar = ctx.GetEnvVar "SOMETHING"

    $"echo {myEnvVar}"
)
```

**Comment by albertwoo** [comment] 2023-06-08 01:53
Because of fsharp limitation I will close this.

Now the runSensitive is a CE operator, but we cannot overload it because fsharp will treat your input as a string instead of FormattableString and throw error says cannot find matchable one.

As we also can do below, so it should be ok even not that perfect.

```fsharp
 run (fun ctx -> ctx.RunSensitiveCommand $"""dotnet {"--version"}""")
```

**Closed by albertwoo** 2023-06-08 01:53 UTC
